// @flow
import { TABLES } from './table-data'

export { TableController as Table } from './table-controller'
export const MODIFY_PARAMS_AND_BONUS_SPELLS_TABLE = TABLES[0].KEY
export const AVERAGE_POWER_PARAMS_TABLE = TABLES[1].KEY
export const AVERAGE_AGILITY_PARAMS_TABLE = TABLES[2].KEY
export const AVERAGE_BODIES_PARAMS_TABLE = TABLES[3].KEY
export const AVERAGE_INTELLIGENCE_PARAMS_TABLE = TABLES[4].KEY
export const AVERAGE_WISDOM_PARAMS_TABLE = TABLES[5].KEY
export const AVERAGE_CHARM_PARAMS_TABLE = TABLES[6].KEY
export const RACIAL_PARAMETER_MODIFIERS_TABLE = TABLES[7].KEY
export const BASIC_SAVE_AND_ATTACK_BONUSES_TABLE = TABLES[8].KEY
export const EXPERIENCE_AND_ADVANTAGES_TABLE = TABLES[9].KEY
export const CLASSES_HIT_POINTS_TABLE = TABLES[10].KEY
export const BARD_TABLE = TABLES[11].KEY
export const BARD_COUNT_SPELLS_TABLE = TABLES[12].KEY
export const BARD_KNOWLENGE_TABLE = TABLES[13].KEY
export const BARD_STARTER_PACK_SKILLS_TABLE = TABLES[14].KEY
export const BARBARIAN_TABLE = TABLES[15].KEY
export const BARBARIAN_STARTER_PACK_TABLE = TABLES[16].KEY
export const WARRIROR_TABLE = TABLES[17].KEY
export const WARRIROR_DWARF_STARTER_PACK_TABLE = TABLES[18].KEY
export const WARRIROR_HUMAN_STARTER_PACK_TABLE = TABLES[19].KEY
export const THIEF_TABLE = TABLES[20].KEY
export const THIEF_STARTER_PACK_TABLE = TABLES[21].KEY
export const DRUID_LVL_TABLE = TABLES[22].KEY
export const DRUID_ANIMAL_COMPANION_LVL_TABLE = TABLES[23].KEY
export const DRUID_4_LVL_ANIMAL_COMPANION_TABLE = TABLES[24].KEY
export const DRUID_7_LVL_ANIMAL_COMPANION_TABLE = TABLES[25].KEY
export const DRUID_10_LVL_ANIMAL_COMPANION_TABLE = TABLES[26].KEY
export const DRUID_13_LVL_ANIMAL_COMPANION_TABLE = TABLES[27].KEY
export const DRUID_16_LVL_ANIMAL_COMPANION_TABLE = TABLES[28].KEY
export const DRUID_STARTER_PACK_TABLE = TABLES[29].KEY
export const PRIEST_LVL_TABLE = TABLES[30].KEY
export const PRIEST_GODS_TABLE = TABLES[31].KEY
export const PRIEST_STARTER_PACK_TABLE = TABLES[32].KEY
export const MAGE_LVL_TABLE = TABLES[33].KEY
export const MAGE_TYPE_AMULETS_TABLE = TABLES[34].KEY
export const MAGE_LVL_DEPENDS_AMULET_TABLE = TABLES[35].KEY
