// @flow
import { TABLES } from './table-data'

export { TableController as Table } from './table-controller'
export const MODIFY_PARAMS_AND_BONUS_SPELLS_TABLE = TABLES[0].KEY
export const AVERAGE_POWER_PARAMS_TABLE = TABLES[1].KEY
export const AVERAGE_AGILITY_PARAMS_TABLE = TABLES[2].KEY
export const AVERAGE_BODIES_PARAMS_TABLE = TABLES[3].KEY
export const AVERAGE_INTELLIGENCE_PARAMS_TABLE = TABLES[4].KEY
export const AVERAGE_WISDOM_PARAMS_TABLE = TABLES[5].KEY
export const AVERAGE_CHARM_PARAMS_TABLE = TABLES[6].KEY
export const RACIAL_PARAMETER_MODIFIERS_TABLE = TABLES[7].KEY
export const BASIC_SAVE_AND_ATTACK_BONUSES_TABLE = TABLES[8].KEY
export const EXPERIENCE_AND_ADVANTAGES_TABLE = TABLES[9].KEY
export const CLASSES_HIT_POINTS_TABLE = TABLES[10].KEY
export const BARD_TABLE = TABLES[11].KEY
export const BARD_COUNT_SPELLS_TABLE = TABLES[12].KEY
export const BARD_KNOWLENGE_TABLE = TABLES[13].KEY
export const BARD_STARTER_PACK_SKILLS_TABLE = TABLES[14].KEY
export const BARBARIAN_TABLE = TABLES[15].KEY
export const BARBARIAN_STARTER_PACK_TABLE = TABLES[16].KEY
